apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: integreatly-deploy
objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: cloud-resource-config
      namespace: ${INSTALLATION_NAMESPACE}
    data:
      managed: >
        {"blobstorage":"${INSTALLATION_STORAGE_TYPE}", "smtpcredentials":"${INSTALLATION_STORAGE_TYPE}", "redis":"${INSTALLATION_STORAGE_TYPE}", "postgres":"${INSTALLATION_STORAGE_TYPE}"}
      workshop: >
        {"blobstorage":"${INSTALLATION_STORAGE_TYPE}", "smtpcredentials":"${INSTALLATION_STORAGE_TYPE}", "redis":"${INSTALLATION_STORAGE_TYPE}", "postgres":"${INSTALLATION_STORAGE_TYPE}"}
parameters:
  - name: INSTALLATION_NAMESPACE
    required: true
  - name: INSTALLATION_STORAGE_TYPE
    displayName: The storage type to be used by the Integreatly products (aws, openshift)
    required: true